trackeet/core/urls.py
from .views import *
from django.urls import path

app_name = 'core'

urlpatterns = [
   path('', dashboard, name='dashboard'),
   path('track-view/', TrackView.as_view(), name='track-view'),
   path('album-view/', AlbumView.as_view(), name='album-view'),
   path('master-view/', MasterView.as_view(), name='master-view'),


   path('vendor/bmi/', VendorBMI.as_view(), name='bmi'),
   path('vendor/ditto/', VendorDitto.as_view(), name='ditto'),
   path('vendor/horus/', VendorHorus.as_view(), name='horus'),
   path('vendor/mcps/', VendorMCPS.as_view(), name='mcps'),
   path('vendor/warner/', VendorWarnerAda.as_view(), name='warner'),
   path('vendor/ppl/', VendorPPL.as_view(), name='ppl'),
   path('vendor/orchid/', VendorOrchid.as_view(), name='orchid'),
   path('vendor/orchad/', VendorOrchard.as_view(), name='orchad'),

   #path('vendor/orchard/', VendorOrchard.as_view(), name='orchard'),
   path('import_vendors/', ImportVendor.as_view(), name='orchard'),


   path('search_album/', search_album, name='search_album'),
   path('search_track/', search_track, name='search_track'),
   path('search_master/', search_master, name='search_master'),
   path('update_track/', update_track, name='update_track'),
   path('update_album/', update_album, name='update_album'),
   path('update_ditto_account/', update_ditto_account, name='update_ditto_account'),
   path('update_bmi_account/', update_bmi_account, name='update_bmi_account'),
   path('update_ppl_account/', update_ppl_account, name='update_ppl_account'),
   path('update_mcps_account/', update_mcps_account, name='update_mcps_account'),



   path('export_track_xls/', export_track_csv, name='export_track_xls'),
   path('export_album_xls/', export_album_csv, name='export_album_xls'),
   path('export_drmsys_xls/', export_drmsys_csv, name='export_drmsys_xls'),
   path('export_accounting_xls/', export_accounting_xls, name='export_accounting_xls'),
   path('export_accounting_csv/', export_accounting_csv, name='export_accounting_csv'),



   
   path('run_special_script/', run_special_script, name='run_special_script'),
   
]

trackeet/trackeet/urls.py

from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('trackx/',include('core.urls', namespace='core')),
    path('',include('home.urls', namespace='home')),
    path('yt/',include('tracker.urls', namespace='tracker')),

  
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

trackeet/tracker/urls.py
from .views import *
from django.urls import path

app_name = 'tracker'

urlpatterns = [
   # path('', Dashboard.as_view(), name='dashboard'),
   path('', reload_data , name='reload-data'),
   path('custom-search/', custom_search , name='custom-search'),
   path('export_query/', export_query , name='export_query'),

   
]

trackeet/tracker/models.py
from django.db import models
from django.conf import settings
from django.utils import timezone

# Create your models here.


class TrackEntries(models.Model):
    title = models.CharField(null=True, blank=True, max_length=500)
    vid_id = models.CharField(null=True, blank=True, max_length=200)
    url = models.CharField(null=True, blank=True, max_length=500)
    duration = models.CharField(null=True, blank=True, max_length=500)
    thumbnail = models.CharField(null=True, blank=True, max_length=500)
    total_views = models.CharField(max_length=500, blank=True, null=True)
    genre = models.CharField(null=True, blank=True, max_length=500)
    likes = models.CharField(null=True, blank=True, max_length=500)
    dislikes = models.CharField(null=True, blank=True, max_length=500)
    commentCount = models.CharField(null=True, blank=True, max_length=500)
    artist = models.CharField(null=True, blank=True, max_length=500)
    export_file = models.FileField(upload_to='documents/tracker/exports', blank=True, null=True)

    def __str__(self):
        return self.title

trackeet/tracker/views.py
from django.shortcuts import render, reverse, get_object_or_404, redirect
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.core.exceptions import ObjectDoesNotExist
from django.contrib import messages
from django.views.generic import ListView, DetailView, View
from django.core.paginator import Paginator
import pandas as pd
from django.core.mail import EmailMultiAlternatives, send_mail, EmailMessage
from django.urls import reverse
import requests
from isodate import parse_duration
from .forms import *
from .models import *
from  core.models import * 
import xlwt
import csv
from datetime import datetime, date
from django.db.models import Q
import os
from googleapiclient.discovery import build
from django.conf import settings
import uuid 
import requests
from email import encoders
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from email.mime.application import MIMEApplication
from email.mime.base import MIMEBase
import random, string
from django.core.mail import EmailMultiAlternatives
from django.template.loader import render_to_string
from django.utils.html import strip_tags

import os

import google_auth_oauthlib.flow
import googleapiclient.errors
from django.core.files import File




api_key = settings.YT_API_KEY

# youtube = build('youtube', 'v3', developerKey=api_key)



def reload_data(request):
    videos = []
    template = 'tracker/search.html'
    if request.method == 'POST':
        search_url = 'https://www.googleapis.com/youtube/v3/search'
        video_url = 'https://www.googleapis.com/youtube/v3/videos'

        search_params = {
            
            'part' : 'snippet,id',
            'q' : request.POST['search'],
            'key' : api_key,
            'maxResults' : 20,
            'type' : 'video,music'
        }

        r = requests.get(search_url, params=search_params)

        results = r.json()['items']

        video_ids = []
        for result in results:
          
            video_ids.append(result['id']['videoId'])

        if request.POST['submit'] == 'lucky':
            return redirect(f'https://www.youtube.com/watch?v={ video_ids[0] }')

        video_params = {
            'key' : api_key,
            'part' : 'snippet,contentDetails,statistics',
            'id' : ','.join(video_ids),
            'videoCategoryId' : 10,
            'maxResults' : 9,
            
        }

        r = requests.get(video_url, params=video_params)

        results = r.json()['items']
     
        

        
        for result in results:
            if 'tags' in result['snippet']:
                if "afro pop" in result['snippet']['tags'] or result['snippet']['description']:
                    print("found one")
                    print(result['snippet']['title'])
            
            video_data = {
                'title' : result['snippet']['title'],
                'id' : result['id'],
                'url' : f'https://www.youtube.com/watch?v={ result["id"] }',
                'duration' : int(parse_duration(result['contentDetails']['duration']).total_seconds() // 60),
                'thumbnail' : result['snippet']['thumbnails']['high']['url']
           
            }

            videos.append(video_data)
                
               
    context = {
        'videos' : videos
    }
    return render(request, template, context)




today = date.today()

my_date = datetime.now().strftime('%m_%d_%Y')
today_date = str(my_date)


def custom_search(request):
    videos = []
    template = "tracker/custom_search.html"
    if request.method == 'POST':
        search_url = 'https://www.googleapis.com/youtube/v3/search'
        video_url = 'https://www.googleapis.com/youtube/v3/videos'

        #most popular
        if request.POST['filter'] == 'most_popular':
            video_params = {
            'key' : api_key,
            'part' : 'snippet,contentDetails,statistics, topicDetails',
            'chart': 'mostPopular',
            'regionCode' : request.POST['region'],
            'videoCategoryId': 10,
            'maxResults' : 20,
             }

            r = requests.get(video_url, params=video_params)

            results = r.json()['items']
           
          
            for result in results:
                
                video_data = {
                    'title' : result['snippet']['title'],
                    'id' : result['id'],
                    'description': result['snippet']['description'],
                    'url' : f'https://www.youtube.com/watch?v={result["id"] }',
                    'duration' : int(parse_duration(result['contentDetails']['duration']).total_seconds() // 60),
                    'thumbnail' : result['snippet']['thumbnails']['high']['url'],
                    'viewCount': result['statistics']['viewCount'],
                    'likeCount': result['statistics']['likeCount'],
                    'commentCount': result['statistics']['commentCount']
                }

                videos.append(video_data)

        #top afropop
        elif request.POST['filter'] == 'top_afropop':
            video_params = {
            'key' : api_key,
            'part' : 'snippet,contentDetails,statistics, topicDetails',
            'chart': 'mostPopular',
            'regionCode' : request.POST['region'],
            'videoCategoryId': 10,
            'maxResults' : 20
             }

            r = requests.get(video_url, params=video_params)

            results = r.json()['items']
           
 
            for result in results:

                if 'afro' or 'afro pop' or 'afrobeats' in result['snippet']['description']:
                    video_data = {
                        'title' : result['snippet']['title'],
                        'id' : result['id'],
                        'description': result['snippet']['description'],
                        'url' : f'https://www.youtube.com/watch?v={ result["id"] }',
                        'duration' : int(parse_duration(result['contentDetails']['duration']).total_seconds() // 60),
                        'thumbnail' : result['snippet']['thumbnails']['high']['url'],
                        'viewCount': result['statistics']['viewCount'],
                        'likeCount': result['statistics']['likeCount'],
                        'commentCount': result['statistics']['commentCount']
                    }

                    videos.append(video_data)

        #top gospel
        elif request.POST['filter'] == 'top_gospel':
            search_params = {
            'part' : 'snippet,id',
            'q' : ' ',
            'key' : api_key,
            'maxResults' : 20,
            'type' : 'video,music',
            'regionCode' : request.POST['region'],
            'topicId': 'm/02mscn',
            'videoCategoryId': 10,
            }

            r = requests.get(search_url, params=search_params)
            print(r.json())

            results = r.json()['items']

            video_ids = []
            for result in results:
            
                video_ids.append(result['id']['videoId'])

            video_params = {
            'key' : api_key,
            'part' : 'snippet,contentDetails,statistics',
            'id' : ','.join(video_ids),
            'videoCategoryId' : 10,
            'maxResults' : 20,
            
                }

            r = requests.get(video_url, params=video_params)

            results = r.json()['items']

            
           
 
            for result in results:
                video_data = {
                    'title' : result['snippet']['title'],
                    'id' : result['id'],
                    'description': result['snippet']['description'],
                    'url' : f'https://www.youtube.com/watch?v={ result["id"] }',
                    'duration' : int(parse_duration(result['contentDetails']['duration']).total_seconds() // 60),
                    'thumbnail' : result['snippet']['thumbnails']['high']['url'],
                    'viewCount': result['statistics']['viewCount'],
                    'likeCount': result['statistics']['likeCount'],
                    'commentCount': result['statistics']['commentCount']
            
                }

                videos.append(video_data)
        # top reggea
        elif request.POST['filter'] == 'reggae':
            search_params = {
            'part' : 'snippet,id',
            'q' : ' ',
            'key' : api_key,
            'maxResults' : 20,
            'type' : 'video,music',
            'regionCode' : request.POST['region'],
            'topicId': '/m/06cqb',
            'videoCategoryId': 10,
            }

            r = requests.get(search_url, params=search_params)
            print(r.json())

            results = r.json()['items']

            video_ids = []
            for result in results:
            
                video_ids.append(result['id']['videoId'])

            video_params = {
            'key' : api_key,
            'part' : 'snippet,contentDetails,statistics',
            'id' : ','.join(video_ids),
            'videoCategoryId' : 10,
            'maxResults' : 20,
            
                }

            r = requests.get(video_url, params=video_params)

            results = r.json()['items']

            
           
 
            for result in results:
                video_data = {
                    'title' : result['snippet']['title'],
                    'id' : result['id'],
                    'description': result['snippet']['description'],
                    'url' : f'https://www.youtube.com/watch?v={ result["id"] }',

trackeet/tracker/templates/tracker/category_search.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Search YouTube</title>
    <!-- Bootstrap core CSS -->
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>
    <!-- Custom styles for this template -->
    <link href="{% static 'assets/album.css' %}" rel="stylesheet">
  </head>
  <body>

<main role="main">

  <section class="jumbotron text-center">
    <div class="container">
      <h1 class="jumbotron-heading">Category </h1>
      <p class="lead text-muted">Get the top nine results on YouTube for your query!</p>
      <form method="POST">
        {% csrf_token %}
        <div class="form-group">
          <div class="row">
            <div class="col-md-6">
              <select class="form-control" name="filter" id="filter">
                <option value="most_popular">Most Popular Music </option>
                <option value="most_viewed_afropop"> Most Viewed Afropop</option>
                <option value="most_liked"> Most Liked Video  </option>
                <option value="most_comments"> Most Engaged Video </option>
              </select>
            </div>
            <div class="col-md-1">
              <p>IN</p>
            </div>
            <div class="col-md-5">
              <select class="form-control" name="region" id="region">
                <option value="NG">Nigeria</option>
                <option value="GB">United Kingdom</option>
                <option value="US">United States</option>
                <option value="DZ">Algeria</option>
                <option value="AR">Argentina</option>
                <option value="AU">Australia</option>
                <option value="AT">Austria</option>
                <option value="AZ">Azerbaijan</option>
                <option value="BH">Bahrain</option>
                <option value="BD">Bangladesh</option>
                <option value="BY">Belarus</option>
                <option value="BE">Belgium</option>
                <option value="BO">Bolivia</option>
                <option value="BA">Bosnia and Herzegovina</option>
                <option value="BR">Brazil</option>
                <option value="BG">Bulgaria</option>
                <option value="CA">Canada</option>
                <option value="CL">Chile</option>
                <option value="CO">Colombia</option>
                <option value="CR">Costa Rica</option>
                <option value="CY">Cyprus</option>
                <option value="DK">Denmark</option>
                <option value="DO">Dominican Republic</option>
                <option value="EC">Ecuador</option>
                <option value="EG">Egypt</option>
                <option value="FR">France</option>
                <option value="DE">Germany</option>
                <option value="GH">Ghana</option>
                <option value="IE">Ireland</option>
                <option value="KE">Kenya</option>
                <option value="LY">Libya</option>
                <option value="MY">Malaysia</option>
                <option value="MX">Mexico</option>
                <option value="MA">Morocco</option>
                <option value="PA">Panama</option>
                <option value="SN">Senegal</option>
                <option value="ZA">South Africa</option>
                <option value="TZ">Tanzania</option>
                <option value="UG">Uganda</option>
                <option value="ZW">Zimbabwe</option>
              </select>
            </div> 
          </div>
        </div>
      <p>
        <button type="submit" name="submit" value="search" class="btn btn-primary my-2">YouTube Search</button>
       
      </p>
      </form>
    </div>
  </section>

  <div class="album py-5 bg-light">
    <div class="container">
      <div class="row">
        {% for video in videos %}
        <div class="col-md-4">
          <div class="card mb-4 shadow-sm">
            <img class="bd-placeholder-img card-img-top" width="100%" height="225" src="{{ video.thumbnail }}" preserveAspectRatio="xMidYMid slice" focusable="false" role="img" aria-label="Placeholder: Thumbnail"></img>
            <div class="card-body">
              <p class="card-text"> <strong>{{ video.title }}</strong> </p>
              <p class="card-text">Description: {{video.description|truncatechars:50}} </p>
              <div class="d-flex justify-content-between align-items-center">
                <strong>
                <p class="card-text"> Views:{{video.viewCount}}  </p>
                <p class="card-text"> Likes:{{video.likeCount}} </p>
                <p class="card-text"> Comments: {{video.commentCount}}  </p>
              </strong>
              </div>
              <div class="btn-group">
                <a type="button" href="{{ video.url }}" target="_blank" class="btn btn-sm btn-outline-secondary">View</a>
              </div>
              <small class="text-muted">{{ video.duration }} mins</small>
            </div>
          </div>
        </div>
        {% endfor %}
      </div>
    </div>
  </div>

</main>
</body>
</html>

trackeet/tracker/templates/tracker/custom_search.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Search YouTube</title>
    <!-- Bootstrap core CSS -->
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>
    <!-- Custom styles for this template -->
    <link href="{% static 'assets/album.css' %}" rel="stylesheet">
  </head>
  <body>

<main role="main">

  <section class="jumbotron text-center">
    <div class="container">
      <h1 class="jumbotron-heading">Location Custom Search</h1>
      <p class="lead text-muted">Get the top results on YouTube for your query!</p>
      <form method="POST">
        {% csrf_token %}
        <div class="form-group">
          <div class="row">
            <div class="col-md-6">
              <select class="form-control" name="filter" id="filter">
                <option value="most_popular">Most Popular Music </option>
                <option value="top_afropop"> Top Afropop </option>
                <!-- <option value="top_juju"> Top Juju Music </option> -->
                <option value="top_highlife"> Top Highlife </option>
                <option value="top_gospel"> Top Gospel  </option>
                <option value="reggae"> Top Reggae  </option>
                <option value="pop_music"> Top Pop Music  </option>
                <option value="jazz"> Jazz Music   </option>
                <option value="rock"> Rock Music  </option>
                <option value="soul"> R&B/Soul Music   </option>
                <option value="country"> Country Music   </option>
              </select>
            </div>
            <div class="col-md-1">
              <p>IN</p>
            </div>
            <div class="col-md-5">
              <select class="form-control" name="region" id="region">
                <option value="NG">Nigeria</option>
                <option value="GB">United Kingdom</option>
                <option value="US">United States</option>
                <option value="DZ">Algeria</option>
                <option value="AR">Argentina</option>
                <option value="AU">Australia</option>
                <option value="AT">Austria</option>
                <option value="AZ">Azerbaijan</option>
                <option value="BH">Bahrain</option>
                <option value="BD">Bangladesh</option>
                <option value="BY">Belarus</option>
                <option value="BE">Belgium</option>
                <option value="BO">Bolivia</option>
                <option value="BA">Bosnia and Herzegovina</option>
                <option value="BR">Brazil</option>
                <option value="BG">Bulgaria</option>
                <option value="CA">Canada</option>
                <option value="CL">Chile</option>
                <option value="CO">Colombia</option>
                <option value="CR">Costa Rica</option>
                <option value="CY">Cyprus</option>
                <option value="DK">Denmark</option>
                <option value="DO">Dominican Republic</option>
                <option value="EC">Ecuador</option>
                <option value="EG">Egypt</option>
                <option value="FR">France</option>
                <option value="DE">Germany</option>
                <option value="GH">Ghana</option>
                <option value="IE">Ireland</option>
                <option value="KE">Kenya</option>
                <option value="LY">Libya</option>
                <option value="MY">Malaysia</option>
                <option value="MX">Mexico</option>
                <option value="MA">Morocco</option>
                <option value="PA">Panama</option>
                <option value="SN">Senegal</option>
                <option value="ZA">South Africa</option>
                <option value="TZ">Tanzania</option>
                <option value="UG">Uganda</option>
                <option value="ZW">Zimbabwe</option>
              </select>
            </div> 
          </div>
        </div>
      <p>
        <button type="submit" name="submit" value="search" class="btn btn-primary my-2">YouTube Search</button>
        <a id="export_btn"  href="#"  class="btn btn-primary my-2">Export Search</a>

       
      </p>
      </form>
    </div>
  </section>

  <div class="album py-5 bg-light">
    <div class="container">
      <div class="row">
        {% for video in videos %}
        <div class="col-md-4">
          <div class="card mb-4 shadow-sm">
            <img class="bd-placeholder-img card-img-top" width="100%" height="225" src="{{ video.thumbnail }}" preserveAspectRatio="xMidYMid slice" focusable="false" role="img" aria-label="Placeholder: Thumbnail"></img>
            <div class="card-body">
              <p class="card-text"> <strong>{{ video.title }}</strong> </p>
              <p class="card-text">Description: {{video.description|truncatechars:50}} </p>
              <div class="d-flex justify-content-between align-items-center">
                <strong>
                <p class="card-text"> Views:{{video.viewCount}}  </p>
                <p class="card-text"> Likes:{{video.likeCount}} </p>
                <p class="card-text"> Comments: {{video.commentCount}}  </p>
              </strong>
              </div>
              <div class="btn-group">
                <a type="button" href="{{ video.url }}" target="_blank" class="btn btn-sm btn-outline-secondary">View</a>
              </div>
              <small class="text-muted">{{ video.duration }} mins</small>
            </div>
          </div>
        </div>
        {% endfor %}
      </div>
    </div>
  </div>

</main>

<script src="https://code.jquery.com/jquery-2.2.4.min.js" integrity="sha256-BbhdlvQf/xTY9gja0Dq3HiwQF8LaCRTXxZKRutelT44=" crossorigin="anonymous"></script>

<script type="text/javascript">

$('#export_btn').click(function(e) {
  e.preventDefault();

  var region = $('#region').val();
  var query = $('#filter').val();


  $.ajax({
            type:"GET", 
            url: "{% url 'tracker:export_query' %}",
            data:{'region':region, 'query':query },
            dataType: 'json',
            success: function (data){
                if (data.status) {
                    console.log(data.msg) 
                } else{
                    console.log("Query didnt run")
             
                
                }
            }
        })

    

});

</script>
</body>
</html>

trackeet/tracker/templates/tracker/search.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Search YouTube</title>
    <!-- Bootstrap core CSS -->
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>
    <!-- Custom styles for this template -->
    <link href="{% static 'assets/album.css' %}" rel="stylesheet">
  </head>
  <body>

<main role="main">

  <section class="jumbotron text-center">
    <div class="container">
      <h1 class="jumbotron-heading">Search YouTube</h1>
      <p class="lead text-muted">Get the top nine results on YouTube for your query!</p>
      <form method="POST">
      <div class="input-group mb-3">
          {% csrf_token %}
          <input type="text" name="search" class="form-control" aria-label="Username">
      </div>
      <p>
        <button type="submit" name="submit" value="search" class="btn btn-primary my-2">YouTube Search</button>
        <button type="submit" name="submit" value="lucky" class="btn btn-secondary my-2">I'm Feeling Lucky</button>
      </p>
       <strong><a style="text-align: center;" href="{% url 'tracker:custom-search' %}">Do a custom search</a></strong>
       <strong><a style="text-align: center;" href="{% url 'tracker:custom-search' %}">Do search by category </a></strong>
      </form>
    </div>
  </section>

  

  <div class="album py-5 bg-light">
    <div class="container">
      <div class="row">
        {% for video in videos %}
        <div class="col-md-4">
          <div class="card mb-4 shadow-sm">
            <img class="bd-placeholder-img card-img-top" width="100%" height="225" src="{{ video.thumbnail }}" preserveAspectRatio="xMidYMid slice" focusable="false" role="img" aria-label="Placeholder: Thumbnail"></img>
            <div class="card-body">
              <p class="card-text">{{ video.title }}</p>
              <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                  <a type="button" href="{{ video.url }}" target="_blank" class="btn btn-sm btn-outline-secondary">View</a>
                </div>
                <small class="text-muted">{{ video.duration }} mins</small>
              </div>
            </div>
          </div>
        </div>
        {% endfor %}
      </div>
      
    </div>
  </div>

  

</main>
</body>
</html>