trackeet/core/urls.py
from .views import *
from django.urls import path

app_name = 'core'

urlpatterns = [
   path('', dashboard, name='dashboard'),
   path('track-view/', TrackView.as_view(), name='track-view'),
   path('album-view/', AlbumView.as_view(), name='album-view'),
   path('master-view/', MasterView.as_view(), name='master-view'),


   path('vendor/bmi/', VendorBMI.as_view(), name='bmi'),
   path('vendor/ditto/', VendorDitto.as_view(), name='ditto'),
   path('vendor/horus/', VendorHorus.as_view(), name='horus'),
   path('vendor/mcps/', VendorMCPS.as_view(), name='mcps'),
   path('vendor/warner/', VendorWarnerAda.as_view(), name='warner'),
   path('vendor/ppl/', VendorPPL.as_view(), name='ppl'),
   path('vendor/orchid/', VendorOrchid.as_view(), name='orchid'),
   path('vendor/orchad/', VendorOrchard.as_view(), name='orchad'),

   #path('vendor/orchard/', VendorOrchard.as_view(), name='orchard'),
   path('import_vendors/', ImportVendor.as_view(), name='orchard'),


   path('search_album/', search_album, name='search_album'),
   path('search_track/', search_track, name='search_track'),
   path('search_master/', search_master, name='search_master'),
   path('update_track/', update_track, name='update_track'),
   path('update_album/', update_album, name='update_album'),
   path('update_ditto_account/', update_ditto_account, name='update_ditto_account'),
   path('update_bmi_account/', update_bmi_account, name='update_bmi_account'),
   path('update_ppl_account/', update_ppl_account, name='update_ppl_account'),
   path('update_mcps_account/', update_mcps_account, name='update_mcps_account'),



   path('export_track_xls/', export_track_csv, name='export_track_xls'),
   path('export_album_xls/', export_album_csv, name='export_album_xls'),
   path('export_drmsys_xls/', export_drmsys_csv, name='export_drmsys_xls'),
   path('export_accounting_xls/', export_accounting_xls, name='export_accounting_xls'),
   path('export_accounting_csv/', export_accounting_csv, name='export_accounting_csv'),



   
   path('run_special_script/', run_special_script, name='run_special_script'),
   
]

trackeet/home/urls.py
from .views import *
from django.urls import path

app_name = 'home'

urlpatterns = [
   path('', homepage, name='homepage'),
   
]

trackeet/trackeet/urls.py

from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('trackx/',include('core.urls', namespace='core')),
    path('',include('home.urls', namespace='home')),
    path('yt/',include('tracker.urls', namespace='tracker')),

  
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

trackeet/tracker/urls.py
from .views import *
from django.urls import path

app_name = 'tracker'

urlpatterns = [
   # path('', Dashboard.as_view(), name='dashboard'),
   path('', reload_data , name='reload-data'),
   path('custom-search/', custom_search , name='custom-search'),
   path('export_query/', export_query , name='export_query'),

   
]

trackeet/home/models.py
from django.db import models

# Create your models here.

trackeet/home/views.py
from django.shortcuts import render

# Create your views here.

def homepage(request):
    
    template = 'home/welcome.html'

    return render(request, template)

trackeet/home/templates/home/welcome.html
{% load static %}

<!DOCTYPE html>
<html lang="zxx" class="no-js">

<head>
	<!-- Mobile Specific Meta -->
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<!-- Favicon-->
	<link rel="shortcut icon" href="{% static 'img/fav.png' %}"> 
	<!-- Author Meta -->
	<meta name="author" content="olusola albert">
	<!-- Meta Description -->
	<meta name="description" content="">
	<!-- Meta Keyword -->
	<meta name="keywords" content="">
	<!-- meta character set -->
	<meta charset="UTF-8">
	<!-- Site Title -->
	<title>Trackeet v.1.1</title>

	<link href="https://fonts.googleapis.com/css?family=Poppins:400,600|Roboto:400,400i,500" rel="stylesheet">
	<!--
			CSS
			============================================= -->
	<link rel="stylesheet" href="{% static 'css/linearicons.css' %}"> 
	<link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}"> 
	<link rel="stylesheet" href="{% static 'css/bootstrap.css' %}"> 
	<link rel="stylesheet" href="{% static 'css/magnific-popup.css' %}"> 
	<link rel="stylesheet" href="{% static 'css/nice-select.css' %}"> 
	<link rel="stylesheet" href="{% static 'css/hexagons.min.css' %}"> 
	<link rel="stylesheet" href="{% static 'css/owl.carousel.css' %}"> 
	<link rel="stylesheet" href="{% static 'css/main.css' %}"> 
</head>

<body>

    <header id="header">
		<div class="container main-menu">
			<div class="row align-items-center justify-content-between d-flex">
				<div id="logo">
					<a href="#"><img src="{% static 'img/logo.png' %}" alt="" title="" /></a>
				</div>
				
			</div>
		</div>
	</header> 

	<!-- <section class="home-banner-area">
		<div class="container">
			<div class="row fullscreen d-flex align-items-center justify-content-between">
				<div class="home-banner-content col-lg-6 col-md-6">
					<h1>
                        The future of music is data 
					</h1>
					<p> Lorem ipsum, dolor sit amet consectetur adipisicing elit. Sed rerum, ab consequatur eum perspiciatis debitis commodi omnis, aliquam harum recusandae eos illo explicabo, officia doloremque. Tempora maxime deleniti omnis facilis.</p>
					<div class="download-button d-flex flex-row justify-content-start">
						
						
					</div>
				</div>
				<div class="banner-img col-lg-4 col-md-6">
					<img class="img-fluid" src="{% static 'img/banner-img.png' %}" alt="">
				</div> 
			</div>
		</div>
	</section> -->
	

	<section class="feature-area">
		<div class="container">
			<div class="row d-flex justify-content-center">
				<div class="col-lg-6">
					<div class="section-title text-center">
						<h2>Welcome back Admin </h2>
						<p>What would you like to explore ?
                        
						</p>
					</div>
				</div>
			</div>
			<div class="row">
				
				<div class="col-lg-4 col-md-6">
					
					<div class="single-feature">
						<a href="{% url 'core:dashboard' %}" class="title">
							<br>
							<h3>Metadata & Statments   </h3>
						</a>
						<p>
							Usage of the Internet is becoming more common due to rapid advancement of technology and power.
						</p>
					</div>
				
				</div>
				
				<div class="col-lg-4 col-md-6">
					<div class="single-feature">
						<a href="{% url 'tracker:reload-data' %}" class="title">
                            <br>
							<h3>Youtube Data Tracker  </h3>
						</a>
						<p>
							Usage of the Internet is becoming more common due to rapid advancement of technology and power.
						</p>
					</div>
				</div>
				<div class="col-lg-4 col-md-6">
					<div class="single-feature">
						<a href="#" class="title">
                            <br>
                            
							<h3>Youtube Reporting System </h3>
						</a>
						<p>
							Usage of the Internet is becoming more common due to rapid advancement of technology and power.
						</p>
					</div>
				</div>

			</div>
		</div>
	</section>
	<!-- End feature Area -->

    <!-- <footer class="footer-area">
        <div class="container">
            <div class="footer-bottom row align-items-center">
                <p class="footer-text m-0 col-lg-6 col-md-12">
                    Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved |Pipminds
                  </p>
            </div>
        </div>
    </footer> -->
	

	<!-- End Footer Area -->

	<script src="{% static 'js/vendor/jquery-2.2.4.min.js' %}"></script> 
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
	 crossorigin="anonymous"></script>
	<script src="{% static 'js/tilt.jquery.min.js' %}"></script>
	<script src="{% static 'js/vendor/bootstrap.min.js' %}"></script>

	<script src="{% static 'js/easing.min.js' %}"></script>
	<script src="{% static 'js/hoverIntent.js' %}"></script>
	<script src="{% static 'js/superfish.min.js' %}"></script>
	<script src="{% static 'js/jquery.ajaxchimp.min.js' %}"></script>
	<script src="{% static 'js/jquery.magnific-popup.min.js' %}"></script>
	<script src="{% static 'js/owl.carousel.min.js' %}"></script>
	<script src="{% static 'js/owl-carousel-thumb.min.js' %}"></script>
	<script src="{% static 'js/hexagons.min.js' %}"></script>
	<script src="{% static 'js/jquery.nice-select.min.js' %}"></script>
	<script src="{%  static 'js/waypoints.min.js' %}"></script>

	<script src="{% static 'js/main.js' %}"></script>
</body>

</html>