trackeet/core/urls.py
from .views import *
from django.urls import path

app_name = 'core'

urlpatterns = [
   path('', dashboard, name='dashboard'),
   path('track-view/', TrackView.as_view(), name='track-view'),
   path('album-view/', AlbumView.as_view(), name='album-view'),
   path('master-view/', MasterView.as_view(), name='master-view'),


   path('vendor/bmi/', VendorBMI.as_view(), name='bmi'),
   path('vendor/ditto/', VendorDitto.as_view(), name='ditto'),
   path('vendor/horus/', VendorHorus.as_view(), name='horus'),
   path('vendor/mcps/', VendorMCPS.as_view(), name='mcps'),
   path('vendor/warner/', VendorWarnerAda.as_view(), name='warner'),
   path('vendor/ppl/', VendorPPL.as_view(), name='ppl'),
   path('vendor/orchid/', VendorOrchid.as_view(), name='orchid'),
   path('vendor/orchad/', VendorOrchard.as_view(), name='orchad'),

   #path('vendor/orchard/', VendorOrchard.as_view(), name='orchard'),
   path('import_vendors/', ImportVendor.as_view(), name='orchard'),


   path('search_album/', search_album, name='search_album'),
   path('search_track/', search_track, name='search_track'),
   path('search_master/', search_master, name='search_master'),
   path('update_track/', update_track, name='update_track'),
   path('update_album/', update_album, name='update_album'),
   path('update_ditto_account/', update_ditto_account, name='update_ditto_account'),
   path('update_bmi_account/', update_bmi_account, name='update_bmi_account'),
   path('update_ppl_account/', update_ppl_account, name='update_ppl_account'),
   path('update_mcps_account/', update_mcps_account, name='update_mcps_account'),



   path('export_track_xls/', export_track_csv, name='export_track_xls'),
   path('export_album_xls/', export_album_csv, name='export_album_xls'),
   path('export_drmsys_xls/', export_drmsys_csv, name='export_drmsys_xls'),
   path('export_accounting_xls/', export_accounting_xls, name='export_accounting_xls'),
   path('export_accounting_csv/', export_accounting_csv, name='export_accounting_csv'),



   
   path('run_special_script/', run_special_script, name='run_special_script'),
   
]

trackeet/export_docs/core/urls.py
from .views import *
from django.urls import path

app_name = 'core'

urlpatterns = [
   path('', dashboard, name='dashboard'),
   path('track-view/', TrackView.as_view(), name='track-view'),
   path('album-view/', AlbumView.as_view(), name='album-view'),
   path('master-view/', MasterView.as_view(), name='master-view'),


   path('vendor/bmi/', VendorBMI.as_view(), name='bmi'),
   path('vendor/ditto/', VendorDitto.as_view(), name='ditto'),
   path('vendor/horus/', VendorHorus.as_view(), name='horus'),
   path('vendor/mcps/', VendorMCPS.as_view(), name='mcps'),
   path('vendor/warner/', VendorWarnerAda.as_view(), name='warner'),
   path('vendor/ppl/', VendorPPL.as_view(), name='ppl'),
   path('vendor/orchid/', VendorOrchid.as_view(), name='orchid'),
   path('vendor/orchard/', VendorOrchard.as_view(), name='orchard'),


   path('search_album/', search_album, name='search_album'),
   path('search_track/', search_track, name='search_track'),
   path('search_master/', search_master, name='search_master'),
   path('update_track/', update_track, name='update_track'),
   path('update_album/', update_album, name='update_album'),
   path('update_ditto_account/', update_ditto_account, name='update_ditto_account'),
   path('update_bmi_account/', update_bmi_account, name='update_bmi_account'),
   path('update_ppl_account/', update_ppl_account, name='update_ppl_account'),
   path('update_mcps_account/', update_mcps_account, name='update_mcps_account'),



   path('export_track_xls/', export_track_csv, name='export_track_xls'),
   path('export_album_xls/', export_album_csv, name='export_album_xls'),
   path('export_drmsys_xls/', export_drmsys_csv, name='export_drmsys_xls'),
   
]

trackeet/trackeet/urls.py

from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('trackx/',include('core.urls', namespace='core')),
    path('',include('home.urls', namespace='home')),
    path('yt/',include('tracker.urls', namespace='tracker')),

  
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

trackeet/core/views.py
from datetime import date
import xlwt, csv, pandas as pd
from django.shortcuts import render, reverse
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.core.exceptions import ObjectDoesNotExist
from django.contrib import messages
from django.views.generic import  View
from django.urls import reverse
import spotipy
import spotipy.oauth2 as oauth2
from spotipy.oauth2 import SpotifyOAuth
from spotipy.oauth2 import SpotifyClientCredentials
import spotipy.util as util
from .forms import *
from .models import *
from .tasks_new import *

#
#
#
#
#
#
today = date.today()
############################
#     DASHBOARD VIEW       #
############################
def dashboard(request):
    template = 'core/index.html'
    track_count = Track.objects.all().count()
    album_count = Album.objects.all().count()
    master_count = Master_DRMSYS.objects.all().count()
    docs = ProcessedDocument.objects.all()
    context = {
        'track_count': track_count,
        'album_count': album_count,
        'master_count': master_count,
        'docs': docs
    }
    return render(request, template, context)
############################
#     ALBUM SEARCH         #
############################
def search_album(request):
    if request.method == "GET":
        product_title = request.GET['product_title']
        product_upc = request.GET['product_upc']
        genre = request.GET['genre']
        product_artist = request.GET['product_artist']
        if product_title is not None and product_title != u"":
            product_title = request.GET['product_title']
            album = Album.objects.filter(product_title__icontains= product_title)
        elif genre is not None and genre != u"":
            genre = request.GET['genre']
            album = Album.objects.filter(genre__icontains= genre)
        elif product_upc is not None and product_upc != u"":
            product_upc = request.GET['product_upc']
            album = Album.objects.filter(product_upc__icontains= product_upc)
        elif product_artist is not None and product_artist != u"":
            product_artist = request.GET['product_artist']
            album = Album.objects.filter(product_artist__icontains= product_artist)
        else:
            album = []
        return render(request, 'core/album_search_result.html', {'album':album})
############################
#     TRACK SEARCH         #
############################
def search_track(request):
    if request.method == "GET":
        display_upc = request.GET['display_upc']
        title = request.GET['title']
        genre = request.GET['genre']
        isrc = request.GET['isrc']
        p_line = request.GET['p_line']
        recording_artist = request.GET['recording_artist']
        artist = request.GET['artist']
        release_name = request.GET['release_name']
        label_name = request.GET['label_name']
        producer = request.GET['producer']
        publisher = request.GET['publisher']
        writer = request.GET['writer']
        arranger = request.GET['arranger']
        territories = request.GET['territories']
        if display_upc is not None and display_upc != u"":
            display_upc = request.GET['display_upc']
            track = Track.objects.filter(display_upc__icontains= display_upc)
        elif title is not None and title != u"":
            title = request.GET['title']
            track = Track.objects.filter(title__icontains= title)
        elif release_name is not None and release_name != u"":
            release_name = request.GET['release_name']
            track = Track.objects.filter(release_name__icontains= release_name)
        elif genre is not None and genre != u"":
            genre = request.GET['genre']
            track = Track.objects.filter(genre__icontains= genre)
        elif territories is not None and territories != u"":
            territories = request.GET['territories']
            track = Track.objects.filter(territories__icontains= territories)
        elif arranger is not None and arranger != u"":
            arranger = request.GET['arranger']
            track = Track.objects.filter(arranger__icontains= arranger)
        elif publisher is not None and publisher != u"":
            publisher = request.GET['publisher']
            track = Track.objects.filter(publisher__icontains= publisher)
        elif producer is not None and producer != u"":
            producer = request.GET['producer']
            track = Track.objects.filter(producer__icontains= producer)
        elif label_name is not None and label_name != u"":
            label_name = request.GET['label_name']
            track = Track.objects.filter(label_name__icontains= label_name)
        elif isrc is not None and isrc != u"":
            isrc = request.GET['isrc']
            track = Track.objects.filter(isrc__icontains= isrc)
        elif p_line is not None and p_line != u"":
            p_line = request.GET['p_line']
            track = Track.objects.filter(p_line__icontains= p_line)
        else:
            track = []
        return render(request, 'core/track_search_result.html', {'track':track})
############################
#  MASTER DRMSYS SEARCH    #
############################
def search_master(request):
    if request.method == "GET":
        display_upc = request.GET['display_upc']
        title = request.GET['title']
        genre = request.GET['genre']
        isrc = request.GET['isrc']
        p_line = request.GET['p_line']
        recording_artist = request.GET['recording_artist']
        artist = request.GET['artist']
        release_name = request.GET['release_name']
        label_name = request.GET['label_name']
        producer = request.GET['producer']
        publisher = request.GET['publisher']
        writer = request.GET['writer']
        arranger = request.GET['arranger']
        territories = request.GET['territories']
        if display_upc is not None and display_upc != u"":
            display_upc = request.GET['display_upc']
            master = Master_DRMSYS.objects.filter(display_upc__icontains= display_upc)
        elif title is not None and title != u"":
            title = request.GET['title']
            master = Master_DRMSYS.objects.filter(title__icontains= title)
            # track = []
        elif arranger is not None and arranger != u"":
            arranger = request.GET['arranger']
            master = Master_DRMSYS.objects.filter(arranger__icontains= arranger)
        elif territories is not None and territories != u"":
            territories = request.GET['territories']
            master = Master_DRMSYS.objects.filter(territories__icontains= territories)
        elif writer is not None and writer != u"":
            writer = request.GET['writer']
            master = Master_DRMSYS.objects.filter(writer__icontains= writer)
        elif genre is not None and genre != u"":
            genre = request.GET['genre']
            master = Master_DRMSYS.objects.filter(genre__icontains= genre)
        elif artist is not None and genre != u"":
            artist = request.GET['artist']
            master = Master_DRMSYS.objects.filter(artist__icontains= artist)
        elif recording_artist is not None and recording_artist != u"":
            recording_artist = request.GET['recording_artist']
            master = Master_DRMSYS.objects.filter(recording_artist__icontains= recording_artist)
        elif isrc is not None and isrc != u"":
            isrc = request.GET['isrc']
            master = Master_DRMSYS.objects.filter(isrc__icontains= isrc)
        elif p_line is not None and p_line != u"":
            p_line = request.GET['p_line']
            master = Master_DRMSYS.objects.filter(p_line__icontains= p_line)
        elif producer is not None and producer != u"":
            producer = request.GET['producer']
            master = Master_DRMSYS.objects.filter(producer__icontains= producer)
        elif publisher is not None and publisher != u"":
            publisher = request.GET['publisher']
            master = Master_DRMSYS.objects.filter(publisher__icontains= publisher)
        elif label_name is not None and label_name != u"":
            label_name = request.GET['label_name']
            master = Master_DRMSYS.objects.filter(label_name__icontains= label_name)
        else:
            master = []
        return render(request, 'core/master_search_result.html', {'master':master})
############################
#     EXPORT TRACK       #
############################
def export_track_xls(request):
    response = HttpResponse(content_type='application/ms-excel')
    f_name = f"track_export_{today}.xls"
    response['Content-Disposition'] = f'attachment; filename={f_name}'
    ####
    wb = xlwt.Workbook(encoding='utf-8')
    ws = wb.add_sheet('Track')
    ####
    row_num = 0
    ####
    font_style = xlwt.XFStyle()
    font_style.font.bold = True
    ####
    columns = ['DisplayUPC', 'VolumeNo', 'TrackNo',  'HiddenTrack',' Title', 'SongVersion', 'Genre',
    'ISRC',  'TrackDuration', 'PreviewClipStartTime', 'PreviewClipDuration', 'P_LINE',
    'Recording Artist', 'Artist', 'Release Name', 'ParentalAdvisory', 'LabelName', 'Producer',
    ' Publisher', 'Writer', 'Arranger', 'Territories', 'Exclusive', 'WholesalePrice', ' Download',
    'SalesStartDate',  'SalesEndDate', 'Error', 'Processed Day', ]
    ###
    for col_num in range(len(columns)):
        ws.write(row_num, col_num, columns[col_num], font_style)
    font_style = xlwt.XFStyle()
    rows = Track.objects.all().values_list( 'display_upc', 'volume_no', 'track_no', 'hidden_track',
    'title','song_version', 'genre', 'isrc', 'track_duration', 'preview_clip_start_time',
    'preview_clip_duration', 'p_line', 'recording_artist', 'artist', 'release_name',

trackeet/core/templates/core/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="Olabanji Albert">
  <title>Trackeet - Reporting Interface</title>
  {% block extra_head %}
  {% endblock %}
	
  <!-- Favicons-->
  <link rel="shortcut icon" href="img/favicon.ico" type="image/x-icon">
  <link rel="apple-touch-icon" type="image/x-icon" href="img/apple-touch-icon-57x57-precomposed.png">
  <link rel="apple-touch-icon" type="image/x-icon" sizes="72x72" href="img/apple-touch-icon-72x72-precomposed.png">
  <link rel="apple-touch-icon" type="image/x-icon" sizes="114x114" href="img/apple-touch-icon-114x114-precomposed.png">
  <link rel="apple-touch-icon" type="image/x-icon" sizes="144x144" href="img/apple-touch-icon-144x144-precomposed.png">

  <!-- GOOGLE WEB FONT -->
  <link href="https://fonts.googleapis.com/css?family=Poppins:300,400,500,600,700,800" rel="stylesheet">
	
  <!-- Bootstrap core CSS-->
  <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet"> 
  <!-- Main styles -->
  <link href="{% static 'css/admin.css' %}" rel="stylesheet">
  <!-- Icon fonts-->
  <link href="{% static 'vendor/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet" type="text/css">  
  <!-- Plugin styles -->
  <link href="{% static 'vendor/datatables/dataTables.bootstrap4.css' %}" rel="stylesheet"> 
  <!-- Your custom styles -->
  <link href="{% static 'css/custom.css' %}" rel="stylesheet"> 
	
</head>

<body class="fixed-nav sticky-footer" id="page-top">
  <!-- Navigation-->
  <nav class="navbar navbar-expand-lg navbar-dark bg-default fixed-top" id="mainNav">
    <a class="navbar-brand" href="{% url 'core:dashboard' %}"><img src="{% static 'img/logo3.png' %}" data-retina="true" alt="" width="auto" height="36"></a>
    <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarResponsive">
      <ul class="navbar-nav navbar-sidenav" id="exampleAccordion">
        <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Dashboard">
          <a class="nav-link" href="{% url 'core:dashboard' %}">
            <i class="fa fa-fw fa-dashboard"></i>
            <span class="nav-link-text">Dashboard</span>
          </a>
        </li>
		  <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Messages">
          <a class="nav-link" href="{% url 'core:album-view' %}">
            <i class="fa fa-fw fa-headphones"></i>
            <span class="nav-link-text">Albums</span>
          </a>
        </li>
		    <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Bookings">
          <a class="nav-link" href="{% url 'core:track-view' %}">
            <i class="fa fa-fw fa-music"></i>
            <span class="nav-link-text">Tracks</span>
          </a>
        </li>
		<li class="nav-item" data-toggle="tooltip" data-placement="right" title="Reviews">
          <a class="nav-link" href="{% url 'core:master-view' %}">
            <i class="fa fa-fw fa-barcode"></i>
            <span class="nav-link-text">Master DRMSYS</span>
          </a>
        </li>
		<li class="nav-item" data-toggle="tooltip" data-placement="right" title="Bookmarks">
          
            <i class="fa fa-fw fa-database"></i>
            <span style="font-style: italic; font-weight: bolder; text-decoration: underline;" class="nav-link-text">VENDORS</span>
          
        </li>
		    <!-- <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Add listing">
          <a class="nav-link" href="#">
            <i class="fa fa-fw fa-plus-circle"></i>
            <span class="nav-link-text">My profile</span>
          </a>
        </li> -->
        <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Vendors">
          <a class="nav-link nav-link-collapse collapsed" data-toggle="collapse" href="#collapseVendor" data-parent="#exampleAccordion">
            <i class="fa fa-fw fa-database"></i>
            <span class="nav-link-text">Publishing</span>
          </a>
          <ul class="sidenav-second-level collapse" id="collapseVendor">
            <li>
              <a href="{% url 'core:bmi' %}">BMI</a>
            </li>
			      <li>
              <a href="{% url 'core:ppl' %}">PPL</a>
            </li>
            <li>
                <a href="{% url 'core:mcps' %}">MCPS</a>
            </li>
            <!-- <li>
              <a href="#">Add Vendors</a>
            </li> -->
          </ul>
        </li>

        <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Distributor">
          <a class="nav-link nav-link-collapse collapsed" data-toggle="collapse" href="#collapseDistributor" data-parent="#exampleAccordion">
            <i class="fa fa-fw fa-database"></i>
            <span class="nav-link-text">Distribution</span>
          </a>
          <ul class="sidenav-second-level collapse" id="collapseDistributor">
            <li>
              <a href="{% url 'core:ditto' %}">DITTO</a>
            </li>
			      <li>
              <a href="{% url 'core:horus' %}">HORUS</a>
            </li>
            <li>
              <a href="#">WARNER ADA </a>
            </li>
            <li>
              <a href="{% url 'core:orchid' %}">Mut Mukson DRMSYS </a>
            </li>
            <li>
              <a href="{% url 'core:orchard' %}">Orchard</a>
            </li>
          </ul>
        </li>

        <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Vendors">
          <a class="nav-link nav-link-collapse collapsed" data-toggle="collapse" href="#collapseVendorPR" data-parent="#exampleAccordion">
            <i class="fa fa-fw fa-database"></i>
            <span class="nav-link-text">Publishing Registration</span>
          </a>
          <ul class="sidenav-second-level collapse" id="collapseVendorPR">
            <li>
              <a href="#">Apple Music</a>
            </li>
			      <li>
              <a href="#">Spotify Music</a>
            </li>
            
            <!-- <li>
              <a href="#">Add Vendors</a>
            </li> -->
          </ul>
        </li>

      </ul>
      <ul class="navbar-nav sidenav-toggler">
        <li class="nav-item">
          <a class="nav-link text-center" id="sidenavToggler">
            <i class="fa fa-fw fa-angle-left"></i>
          </a>
        </li>
      </ul>

      
      <ul class="navbar-nav ml-auto">
       
        
        
        <li class="nav-item">
          <a class="nav-link" data-toggle="modal" data-target="#exampleModal">
            <i class="fa fa-fw fa-sign-out"></i>ADMIN</a>
        </li>
      </ul>



    </div>
  </nav>
  <!-- /Navigation-->
  {% block content  %}


    {% endblock content %}



    <footer class="sticky-footer">
      <div class="container">
        <div class="text-center">
          <small>Copyright © TRACKEET 2020</small>
        </div>
      </div>
    </footer>
    <!-- Scroll to Top Button-->
    <a class="scroll-to-top rounded" href="#page-top">
      <i class="fa fa-angle-up"></i>
    </a>
    <!-- Logout Modal-->
    <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
            <button class="close" type="button" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">×</span>
            </button>
          </div>
          <div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
          <div class="modal-footer">
            <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
            <a class="btn btn-primary" href="#">Logout</a>
          </div>
        </div>
      </div>
    </div>
    {% block search_modal %}
    {% endblock %}
    
    {% block addRecord_modal %}
    {% endblock %}
    <!-- Bootstrap core JavaScript-->
    <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script> 
    <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script> 
    <!-- Core plugin JavaScript-->
    <script src="{% static 'vendor/jquery-easing/jquery.easing.min.js' %}"></script> 
    <!-- Page level plugin JavaScript-->
    <script src="{% static 'vendor/chart.js/Chart.js' %}"></script> 
    <script src="{% static 'vendor/datatables/jquery.dataTables.js' %}"></script> 
    <script src="{% static 'vendor/datatables/dataTables.bootstrap4.js' %}"></script> 
	<script src="{% static 'vendor/jquery.selectbox-0.2.js' %}"></script> 
	<script src="{% static 'vendor/retina-replace.min.js' %}"></script> 
  <script src="{% static 'vendor/jquery.magnific-popup.min.js' %}"></script> 
  
    <!-- Custom scripts for all pages-->
    <script src="{% static 'js/admin.js' %}"></script> 
	<!-- Custom scripts for this page-->
    <script src="{% static 'js/admin-charts.js' %}"></script> 
    {% block extra_script %}
    {% endblock %}
	
</body>
</html>

trackeet/core/templates/core/master_search_result.html
{% extends 'core/base.html' %}
{% load static %}

{% block extra_head %}
<link href="{% static 'vendor/dropzone.css' %}" rel="stylesheet"> 
<link href="{% static 'css/date_picker.css' %}" rel="stylesheet"> 
{% endblock %}
{% block content %}



      <div class="card-body">
        <div class="table-responsive">
          <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
            <thead>
              <tr>
          <th> Arranger </th>
					<th> Artist  </th>
					<th> Artist Url</th> 
					<th> Bpm   </th>
					<th> C LINE       </th>
					<th> Data Type    </th>
					<th> Deleted    </th>
					<th> Display UPC  </th>
					<th> Download    </th>
					<th> Error    </th>
					<th> Exclusive    </th>
					<th> Genre    </th>
					<th> Genre_alt    </th>
					<th> Genre_sub    </th>
					<th> Genre_subalt    </th>
					<th> Hidden_track    </th>
					<th> ISRC    </th>
					<th> Itunes_Link    </th>
					<th> Label Catalogno    </th>
					<th> Label Name    </th>
					<th> Language    </th>
					<th> Manufacturer UPC    </th>
					<!-- <th> Master Carveouts    </th> -->
					<th> P_LINE   </th>
					<th> Parental Advisory    </th>
					<th> Preview Clip Duration    </th>
					<th> preview Clip Start Time    </th>
					<th> Price Band    </th>
					<th> Producer    </th>
					<th> Publisher    </th>
					<th> Recording Artist    </th>
					<th> Release Date    </th>
					<th> Release Name    </th>
					<th> Royalty Rate    </th>
					<th> Sales End Date    </th>
					<th> Sales Start Date    </th>
					<th> Song Version    </th>
					<th> Territories    </th>
					<!-- <th> Territories Carveouts    </th> -->
					<th> Title    </th>
					<th> Total Tracks    </th>
					<th> Total Volumes    </th>
					<th> Track Duration    </th>
					<th> Track No    </th>
					<th> Vendor Name    </th>
					<th> Volume No    </th>
					<th> Wholesale Price    </th>
					<th> Writer    </th>
					<th> zIDKey_UPCISRC    </th>
              </tr>
            </thead>
            <tbody>
                {% if master %}
                {% for item in master %}
              <tr>
                <td>{{item.arranger}}</td>
                <td>{{item.artist}}</td>
                <td>{{item.artist_url}}</td>
                <td>{{item.bpm}}</td>
                <td>{{item.c_line}}</td>
                <td>{{item.data_type}}</td>
                <td>{{item.deleted}}</td>
                <td>{{item.display_upc}}</td>
                <td>{{item.download}}</td>
                <td>{{item.error}}</td>
                <td>{{item.exclusive}}</td>
                <td>{{item.genre}}</td>
                <td>{{item.genre_alt}}</td>
                <td>{{item.genre_sub}}</td>
                <td>{{item.genre_subalt}}</td>
                <td>{{item.hidden_track}}</td>
                <td>{{item.isrc}}</td>
                <td>{{item.itunes_link}}</td>
                <td>{{item.label_catalogno}}</td>
                <td>{{item.label_name}}</td>
                <td>{{item.language}}</td>
                <td>{{item.manufacturer_upc}}</td>
                <!-- <td>{{item.master_carveouts}}</td> -->
                <td>{{item.p_line}}</td>
                <td>{{item.parental_advisory}}</td>
                <td>{{item.preview_clip_duration}}</td>
                <td>{{item.preview_clip_start_time}}</td>
                <td>{{item.price_band}}</td>
                <td>{{item.producer}}</td>
                <td>{{item.publisher}}</td>
                <td>{{item.recording_artist}}</td>
                <td>{{item.release_date}}</td>
                <td>{{item.release_name}}</td>
                <td>{{item.royalty_rate}}</td>
                <td>{{item.sales_end_date}}</td>
                <td>{{item.sales_start_date}}</td>
                <td>{{item.song_version}}</td>
                <td>{{item.territories}}</td>
                <!-- <td>{{item.territories_carveouts}}</td> -->
                <td>{{item.title}}</td>
                <td>{{item.total_tracks}}</td>
                <td>{{item.total_volumes}}</td>
                <td>{{item.track_duration}}</td>
                <td>{{item.track_no}}</td>
                <td>{{item.vendor_name}}</td>
                <td>{{item.volume_no}}</td>
                <td>{{item.wholesale_price}}</td>
                <td>{{item.writer}}</td>
                <td>{{item.zIDKey_UPCISRC}}</td>
              </tr>
              {% endfor %}
              {% else %}
                <p>No drmsys record found.</p>
            {% endif %}
              
            </tbody>
          </table>
        </div>
      </div>
     
{%  endblock %}

    <!-- /.container-wrapper-->

{% block extra_script %}

<script src="{% static 'vendor/dropzone.min.js' %}"></script> 
<script src="{% static 'vendor/bootstrap-datepicker.js' %}"></script> 
<script>$('input.date-pick').datepicker();</script>

{% endblock %}
   